#!/bin/bash

P=""

echo ${BASH_ARGV[*]}
for i in ${BASH_ARGV[*]}
do
  P="$i $P"
done

echo $P
echo ${@:1}

echo "Running player code with arguments: player ${@:1} ..."

javac -classpath ".:zookeeper-3.4.12.jar" ConnectionCreator.java
javac -classpath ".:zookeeper-3.4.12.jar" Player.java
java -classpath ".:zookeeper-3.4.12.jar:log4j-1.2.17.jar:slf4j-api-1.7.25.jar:slf4j-log4j12-1.7.25.jar" Player player ${@:1}
